name: Build Binary File

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - { goos: "darwin", goarch: "amd64" }
        - { goos: "darwin", goarch: "arm64" }
        - { goos: "linux", goarch: "386" }
        - { goos: "linux", goarch: "amd64" }
        - { goos: "linux", goarch: "arm" }
        - { goos: "linux", goarch: "arm64" }
        - { goos: "windows", goarch: "386" }
        - { goos: "windows", goarch: "amd64" }
        - { goos: "windows", goarch: "arm64" }

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.24.1'

    - name: Build
      env:
        GOOS: ${{ matrix.platform.goos }}
        GOARCH: ${{ matrix.platform.goarch }}
      run: |
        mkdir -p bin
        if [ "${{ matrix.platform.goos }}" == "windows" ]; then
          go build -o bin/simcdn-${{ matrix.platform.goos }}-${{ matrix.platform.goarch }}.exe
        else
          go build -o bin/simcdn-${{ matrix.platform.goos }}-${{ matrix.platform.goarch }}
        fi

    - name: Test
      run: go test -v ./...

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: simcdn-${{ matrix.platform.goos }}-${{ matrix.platform.goarch }}
        path: bin/simcdn-${{ matrix.platform.goos }}-${{ matrix.platform.goarch }}${{ matrix.platform.goos == 'windows' && '.exe' || '' }}
